export const CLASSROOM_LIMITS = {
	MAX_ACTIVE_CLASSES_PER_TEACHER: 8,
	MAX_ACTIVE_COURSES_PER_TEACHER: 30,
	MAX_COURSES_PER_CLASSROOM: 15,
	MAX_STUDENTS_PER_CLASSROOM: 50,
	MAX_STUDENTS_PER_COURSE: 50,
} as const;
