export {
  quizEditorApi,
  useCreateQuizMutation,
  useUpdateQuizMutation,
  usePublishQuizMutation,
  useDeleteQuizMutation,
  useGetQuizForEditorQuery,
  useGetMyDraftsQuery,
  useCreateQuestionMutation,
  useUpdateQuestionMutation,
  useDeleteQuestionMutation,
  useDuplicateQuestionMutation,
  useReorderQuestionsMutation,
  useUploadImageMutation,
} from './api/quizEditorApi';

export type {
  QuestionType,
  VariantType,
  EditorVariant,
  EditorQuestion,
  EditorQuiz,
  CreateQuizPayload,
  UpdateQuizPayload,
  CreateQuestionPayload,
  UpdateQuestionPayload,
  ReorderPayload,
  PublishValidationError,
  PublishErrorResponse,
  SaveStatus,
} from './models';

export { useAutoSave } from './hooks/useAutoSave';

export {
  QuizEditorLayout,
  PublishModal,
  EditorHeader,
  QuestionEditor,
  QuestionList,
  QuestionSettings,
  QuestionTypeSelector,
  TypeAnswerEditor,
  VariantEditor,
  DraftsTopbar,
  DraftsHero,
  DraftsToolbar,
  DraftCard,
  DraftCreateCard,
  DraftsGrid,
  DEFAULT_COVER_GRADIENT,
  type QuizEditorLayoutProps,
  type PublishModalProps,
  type EditorHeaderProps,
  type QuestionEditorProps,
  type QuestionListProps,
  type SortableItemProps,
  type QuestionSettingsProps,
  type QuestionTypeSelectorProps,
  type TypeAnswerEditorProps,
  type VariantEditorProps,
  type DraftsTopbarProps,
  type DraftsHeroProps,
  type DraftsToolbarProps,
  type DraftSortField,
  type DraftSortOrder,
  type DraftCardProps,
  type DraftCreateCardProps,
  type DraftsGridProps,
} from './ui';
