export {
  baseApi,
  getAuthToken,
  setAuthToken,
  removeAuthToken,
  getAuthHeaders,
  getToken,
  setToken,
  removeToken,
  ApiError,
  apiFetch,
  apiCheckUnique,
  apiSendCode,
  apiRegister,
  apiLogin,
  apiMe,
  type ApiErrorResponse,
  type PaginationParams,
  type PaginatedResult,
} from './api';
export {
  API_ENDPOINTS,
  STORAGE_KEYS,
  COLORS,
  type ColorKey,
  BASE_URL,
  IS_DEV,
  IS_PROD,
  FONT_SIZES,
  type FontSizeKey,
} from './constants';
export { useLocale } from './hooks';
export { FONTS } from './theme';
export { pickImage, type PickImageOptions } from './tools';
export {
  Layout,
  TeacherLayout,
  StudentLayout,
  ProtectedRoute,
  PublicRoute,
  AiIcon,
  ArrowIcon,
  BinIcon,
  CloseIcon,
  EnterIcon,
  MultipleIcon,
  MultuipleIcon,
  OneAnswerIcon,
  PlusIcon,
  PublicIcon,
  UploadIcon,
  ViewEyeIcon,
  CopyIcon,
  CheckIcon,
  PlayIcon,
  SettingsIcon,
  SparkleIcon,
  ExpandIcon,
  NeutralCheckIcon,
  CorrectCheckIcon,
  IncorrectCrossIcon,
  LogoIcon,
  TimerIcon,
  type IconProps,
} from './ui';
export {
  getLocale,
  setLocale,
  toggleLocale,
  t,
  pluralize,
  pluralizeUk,
  formatPlural,
  pluralizeQuestions,
  pluralizeAnswers,
  pluralizePoints,
  pluralizeParticipants,
  subscribe,
  type Locale,
  type PluralWords,
  LocaleContext,
  LocaleProvider,
} from './i18n';

